workflows:
  ios_testflight:
    name: iOS TestFlight
    max_build_duration: 60
    environment:
      xcode: latest
      groups:
        - app_store_connect
        - ios_signing
      vars:
        XCODE_PROJECT: "ios/FuerzaHomeServices.xcodeproj"
        XCODE_SCHEME: "FuerzaHomeServices"
        BUNDLE_ID: "com.fuerza.homeservices"
    scripts:
      - name: Generate Xcode project (XcodeGen)
        script: |
          cd ios
          brew install xcodegen
          xcodegen generate
      - name: Build IPA
        script: |
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath ios/build/FuerzaHomeServices.xcarchive \
            clean archive
          xcodebuild \
            -exportArchive \
            -archivePath ios/build/FuerzaHomeServices.xcarchive \
            -exportOptionsPlist ios/exportOptions.plist \
            -exportPath ios/build/ipa
    artifacts:
      - ios/build/ipa/*.ipa
      - ios/build/FuerzaHomeServices.xcarchive/dSYMs/*.dSYM
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        beta_groups:
          - "Internal Testers"


